In [1]:
#Pseudoinverse
import numpy as np
from scipy.special import logit

In [2]:
# Activation functions
def ReLU(x):
    return x * (x > 0)

def Sig(x):
    return 1/(1+np.exp(-x))

def onehot(X):
    T = np.zeros((X.shape[0],np.max(X)+1))
    T[np.arange(len(X)),X] = 1 #Set T[i,X[i]] to 1
    return T

# feed forward function
def ff(w0,w1,w2,b0,b1,b2,x):
    # First Hidden calculations
    h0 = x.dot(w0)+ b0 
    h0 = ReLU(h0)
 
  # Second Hidden calculations
    h1 = h0.dot(w1) + b1
    h1 = ReLU(h1)

  # output calculations
    ff = h1.dot(w2) + b2
    ff = Sig(ff)
    return ff

In [3]:
# data preprocessing
    # train data
xtrain = np.loadtxt('xtrain.txt', delimiter=',')
xtrain /= 255
ytrain = np.loadtxt('ytrain.txt', delimiter=',').astype(int)
ytrain = onehot(ytrain)
   #test data
xtest = np.loadtxt('xtest.txt', delimiter=',')
xtest /= 255
ytest = np.loadtxt('ytest.txt', delimiter=',').astype(int)

In [4]:
# randomly-chosen set of weights and biase
s = 0.2
W0 = (np.random.rand(784,512)-0.5)*s
W1 = (np.random.rand(512,512)-0.5)*s

B0 = (np.random.rand(512,)-0.5)*s
B1 = (np.random.rand(512,)-0.5)*s

In [5]:
# WieghtsPseudoinvers
H0 = ReLU(xtrain.dot(W0) + B0)
H1 = ReLU(H0.dot(W1) + B1)
ytrain_transformed = ytrain * 0.9 + 0.05
Y_l = logit(ytrain_transformed)
B2 = np.mean(Y_l,0)
W2 = np.linalg.pinv(H1).dot(Y_l - B2)

In [8]:
# test 
Output = ff(W0,W1,W2,B0,B1,B2,xtest)
Output = np.argmax(Output, axis = 1)


#ytrain1 = np.loadtxt('ytrain.txt', delimiter=',').astype(int)
accuracy = ((np.count_nonzero(Output==ytest))/10000)*100   
print('accuracy:', round(accuracy,2), '%')

accuracy: 91.3 %


In [7]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix        
cm = confusion_matrix(Output, ytest)
print(cm)

[[ 952    0   12    2    0   14    9    5   11    8]
 [   1 1123    8    4    8    7    3   18    6    8]
 [   3    2  906   22    6    2    5   18    7    3]
 [   3    1   17  916    1   30    2    1   24    4]
 [   2    0   12    4  891   13   12   13   17   49]
 [   3    1    4   17    4  767   10    6   21   11]
 [   9    4   13    4   14   18  912    2   12    8]
 [   3    1   21   17    3   12    1  937    9   33]
 [   4    3   35   13    9   22    4    3  849    8]
 [   0    0    4   11   46    7    0   25   18  877]]
